---
- name: create repo file for jenkins
  template: src=jenkins.repo dest=/etc/yum.repos.d/jenkins.repo owner=root group=root mode=0645
  tags:
    - yum
    - jenkins

- name: copy jenkins key file
  copy: src=jenkins-ci.org.key dest=/etc/pki/rpm-gpg/jenkins-ci.org.key owner=root group=root mode=0644
  tags:
        - yum
        - jenkins

- name: install jenkins packages loop
  yum: name={{ item }} state=installed
  with_items:
    - java-1.6.0-openjdk
    - jenkins
  tags:
    - jenkins
    - yum
    - packages

- name: ensure jenkins user has ssh key
  user: name=jenkins state=present generate_ssh_key=yes shell=/bin/bash
  tags:
    - jenkins
    - users

- name: make jenkins plugin dir
  file: path=/var/lib/jenkins/plugins state=directory owner=jenkins group=jenkins
  tags:
    - jenkins

# I like to disable more than this, but you may not want to
- name: disable jenkins plugins
  copy: dest=/var/lib/jenkins/plugins/{{ item }}.jpi.disabled src=/dev/null
  with_items:
    - translation
  tags:
    - jenkins

- name: enable jenkins
  service: name=jenkins enabled=yes
  tags:
    - jenkins

- name: start jenkins
  service: name=jenkins state=started
  tags:
    - jenkins

- name: grep for {{ jenkins_web_port }} in /etc/sysconfig/iptables
  command: /bin/grep -- '-A INPUT -m state --state NEW -m tcp -p tcp --dport {{ jenkins_web_port }} -j ACCEPT' /etc/sysconfig/iptables
  register: jenkins_port
  changed_when: False
  ignore_errors: True
  tags:
    - jenkins
    - iptables

- name: run lokkit for iptables of jenkins port
  command: /usr/sbin/lokkit -p {{ jenkins_web_port }}:tcp
  when: "jenkins_port.rc != 0"
  tags:
    - jenkins
    - iptables
